version: '3.8'

services:

  online-school-api:
    container_name: online-school-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './:/app:rw'
      - '/app/node_modules/'
    depends_on:
      - online-school-db
    networks:
      - online-school-network


  online-school-db:
    container_name: online-school-db
    image: 'mongo'
    ports:
      - '27017:27017'
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes: 
      - "online-school-volume:/data/db"
    networks:
      - online-school-network
      
  


  # Utility containers
  # For example: docker-compose run --rm api-npm i -D @types/express
  api-npm:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - './:/app:rw'
    networks:
      - online-school-network

  api-npx:
    image: node:20.16.0-alpine
    working_dir: /app
    entrypoint: ['npx']
    volumes:
      - './:/app:rw'
    networks:
      - online-school-network


volumes:
  online-school-volume:
    driver: local

networks:
 online-school-network:
   driver: bridge