import { Column, Entity, ObjectIdColumn, PrimaryColumn } from "typeorm";

@Entity()
export class Student {

    @ObjectIdColumn()
    _id:string; // private id whitch generated by mongo
    
    @PrimaryColumn()
    id:string; // public id for search

    @Column()
    firstName:string;
    
    @Column()
    lastName:string;
}