import { Column, Entity, ObjectIdColumn, PrimaryColumn } from "typeorm";

@Entity()
export class Lesson {

    @ObjectIdColumn()
    _id:string; // private id whitch generated by mongo
    
    @PrimaryColumn()
    id:string; // public id for search

    @Column()
    name:string;
    
    @Column()
    startDate:string;

    @Column()
    endDate:string;


    @Column()
    students:string[];

}